### ISSUE TITLE
Missing using static equivalent in F# 

### ISSUE THREAD

**Issue by NinoFloris** [fsharp/fslang-design#216] opened 2017-07-24 19:47 UTC
Basically missing this suggestion in this repo:
 https://fslang.uservoice.com/forums/245727-f-language/suggestions/6958404-allow-opening-of-static-classes-matching-the-c-d

**Comment by rmunn** [comment] 2017-07-31 03:38
That suggestion has been migrated to https://github.com/fsharp/fslang-suggestions/issues/383

**Comment by cartermp** [comment] 2018-06-07 04:48
Closing as dupe of the fslang-suggestions issue

**Closed by cartermp** 2018-06-07 04:48 UTC
